# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

VM_BOX = "ubuntu/focal64"
MASTER_NAME = "kmaster"
WORKER_NAME = "kworker"
IP_SUBNET = "192.168.95."

Vagrant.configure("2") do |config|
  config.vm.box = VM_BOX
  config.vm.box_check_update = false

  config.vm.define "kube-master" do |master|
    master.vm.provider "virtualbox" do |vb|
      vb.name = MASTER_NAME
      vb.memory = 2048
      vb.cpus = 2
    end
    master.vm.hostname = MASTER_NAME
    master.vm.network "private_network", ip: IP_SUBNET + "5"
    master.vm.network "forwarded_port", guest: 22, host: 65001
    master.vm.provision "host-setup", type: "shell", path: "../host-setup.sh"
    master.vm.provision "dns-setup", type: "shell", path: "../dns-setup.sh"
  end

  config.vm.define "kube-worker" do |worker|
    worker.vm.provider "virtualbox" do |vb|
      vb.name = WORKER_NAME
      vb.memory = 2048
      vb.cpus = 2
    end
    worker.vm.hostname = WORKER_NAME
    worker.vm.network "private_network", ip: IP_SUBNET + "6"
    worker.vm.network "forwarded_port", guest: 22, host: 65002
    worker.vm.provision "host-setup", type: "shell", path: "../host-setup.sh"
    worker.vm.provision "dns-setup", type: "shell", path: "../dns-setup.sh"
  end
end
