# This is only needed for further use of the ansible playbook after initial vagrant deployment.
# Always ensure that the hostnames and ip addresses match the vagrant config
all:
  children:
    kube_master:
      hosts:
        kube-master:
          ansible_host: 192.168.95.5
    kube_worker:
      hosts:
        kube-worker1:
          ansible_host: 192.168.95.6
        kube-worker2:
          ansible_host: 192.168.95.7